apiVersion: v1
kind: Secret
metadata:
  name: product-service-secrets
  labels:
    app: product-service
type: Opaque
stringData:
  secret-key: "ZGphbmdvLWluc2VjdXJlLXN0LTE3MCE0JDRhZiFeN3h5amowPSUxMnQ5JjdwKmMhNWJxPUB2OXNeaSgmKSkgdGQ4a2E="
  mongodb-user: "mongodb-user"
  mongodb-password: "mongodb-password"
  jwt-secret-key: "c3VwZXItc3Ryb25nLXJhbmRvbS1zZWNyZXQtMTIzIUAjYWRtaW4="
